insert into users (id, first_name, last_name, email, password, image, type_id, created_at, updated_at) values (1, 'Rayna', 'Sambidge', 'rsambidge0@gmpg.org', 'JtXVx0vH4En', 'https://robohash.org/ipsamdeseruntdoloremque.png?size=50x50&set=set1', 1, '11/25/2021', '8/16/2021');
insert into users (id, first_name, last_name, email, password, image, type_id, created_at, updated_at) values (2, 'Law', 'Trodler', 'ltrodler1@huffingtonpost.com', 'fjjah2CgMp', 'https://robohash.org/repellendusexplicabout.png?size=50x50&set=set1', 2, '4/1/2021', '2/7/2021');
insert into users (id, first_name, last_name, email, password, image, type_id, created_at, updated_at) values (3, 'Amy', 'Baildon', 'abaildon2@issuu.com', 'kmn5vsCvE33Z', 'https://robohash.org/estsaepefugiat.png?size=50x50&set=set1', 3, '9/20/2021', '12/3/2021');
insert into users (id, first_name, last_name, email, password, image, type_id, created_at, updated_at) values (4, 'Matthus', 'Dewick', 'mdewick3@elpais.com', 'TE27XEUM', 'https://robohash.org/verononet.png?size=50x50&set=set1', 4, '1/5/2021', '9/3/2021');
insert into users (id, first_name, last_name, email, password, image, type_id, created_at, updated_at) values (5, 'Flora', 'Faichnie', 'ffaichnie4@ibm.com', 'aKDjyb', 'https://robohash.org/quifugiattemporibus.png?size=50x50&set=set1', 5, '11/23/2021', '12/31/2020');
insert into users (id, first_name, last_name, email, password, image, type_id, created_at, updated_at) values (6, 'Hoyt', 'Merryfield', 'hmerryfield5@sciencedirect.com', 'PHw73PC7Ye', 'https://robohash.org/possimusvoluptascorporis.png?size=50x50&set=set1', 6, '7/21/2021', '9/1/2021');
insert into users (id, first_name, last_name, email, password, image, type_id, created_at, updated_at) values (7, 'Hadleigh', 'Kamien', 'hkamien6@pcworld.com', 'EV5Jru', 'https://robohash.org/laboreodioenim.png?size=50x50&set=set1', 7, '4/6/2021', '9/3/2021');
insert into users (id, first_name, last_name, email, password, image, type_id, created_at, updated_at) values (8, 'Bearnard', 'Chamberlain', 'bchamberlain7@narod.ru', '02qByZ', 'https://robohash.org/quidemetaperiam.png?size=50x50&set=set1', 8, '6/21/2021', '1/28/2021');
insert into users (id, first_name, last_name, email, password, image, type_id, created_at, updated_at) values (9, 'Dan', 'Corrie', 'dcorrie8@ning.com', 'uXbvzC0RwLGl', 'https://robohash.org/repudiandaeetmagni.png?size=50x50&set=set1', 9, '2/23/2021', '5/7/2021');
insert into users (id, first_name, last_name, email, password, image, type_id, created_at, updated_at) values (10, 'Lorie', 'Gabel', 'lgabel9@unicef.org', 'QVT1AGTZh', 'https://robohash.org/voluptateadexcepturi.png?size=50x50&set=set1', 10, '7/29/2021', '2/10/2021');


insert into Poducts (id, name, description, image, classification_id, variety_id, price, featured, created_at, updated_at) values (1, 'praesent blandit lacinia erat vestibulum', 'pellentesque viverra pede ac diam', 'https://robohash.org/voluptatesvoluptatibusid.png?size=50x50&set=set1', 1, 1, 9377.63, false, '12/28/2020', '3/12/2021');
insert into Poducts (id, name, description, image, classification_id, variety_id, price, featured, created_at, updated_at) values (2, 'dapibus augue vel accumsan', 'magna bibendum imperdiet nullam orci', 'https://robohash.org/uttemporibusrerum.png?size=50x50&set=set1', 2, 2, 6747.0, true, '9/30/2021', '3/22/2021');
insert into Poducts (id, name, description, image, classification_id, variety_id, price, featured, created_at, updated_at) values (3, 'sapien quis libero nullam', 'dui luctus rutrum nulla tellus', 'https://robohash.org/estoptiominima.png?size=50x50&set=set1', 3, 3, 3796.08, false, '2/1/2021', '12/21/2020');
insert into Poducts (id, name, description, image, classification_id, variety_id, price, featured, created_at, updated_at) values (4, 'erat eros viverra eget', 'non velit donec diam neque', 'https://robohash.org/asperioresquaeratquod.png?size=50x50&set=set1', 4, 4, 2616.7, true, '2/22/2021', '6/30/2021');
insert into Poducts (id, name, description, image, classification_id, variety_id, price, featured, created_at, updated_at) values (5, 'orci pede venenatis non', 'vulputate vitae nisl aenean lectus', 'https://robohash.org/veritatisrepellendusasperiores.png?size=50x50&set=set1', 5, 5, 3572.06, false, '8/9/2021', '9/11/2021');
insert into Poducts (id, name, description, image, classification_id, variety_id, price, featured, created_at, updated_at) values (6, 'interdum eu tincidunt in leo', 'ultrices phasellus id sapien in', 'https://robohash.org/temporibusporroaut.png?size=50x50&set=set1', 6, 6, 5798.49, true, '11/30/2021', '4/6/2021');
insert into Poducts (id, name, description, image, classification_id, variety_id, price, featured, created_at, updated_at) values (7, 'semper sapien a libero nam', 'vestibulum ante ipsum primis in', 'https://robohash.org/molestiaeessequo.png?size=50x50&set=set1', 7, 7, 4524.8, true, '12/29/2020', '6/11/2021');
insert into Poducts (id, name, description, image, classification_id, variety_id, price, featured, created_at, updated_at) values (8, 'id nulla ultrices aliquet', 'consequat dui nec nisi volutpat', 'https://robohash.org/etcommodivitae.png?size=50x50&set=set1', 8, 8, 8358.84, false, '4/27/2021', '10/6/2021');
insert into Poducts (id, name, description, image, classification_id, variety_id, price, featured, created_at, updated_at) values (9, 'duis faucibus accumsan odio', 'at dolor quis odio consequat', 'https://robohash.org/occaecatiestquisquam.png?size=50x50&set=set1', 9, 9, 6593.22, true, '9/14/2021', '10/21/2021');
insert into Poducts (id, name, description, image, classification_id, variety_id, price, featured, created_at, updated_at) values (10, 'neque aenean auctor gravida', 'varius ut blandit non interdum', 'https://robohash.org/sapientenihilvelit.png?size=50x50&set=set1', 10, 10, 5875.57, false, '7/5/2021', '12/26/2020');
